import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tkachenko Denis Front-end developer",
  description: "Generated by create next app and Material UI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{backgroundColor: '#222', color: '#EEEEEE'}}>{children}</body>
    </html>
  );
}
